---
- hosts: mikrotik-cell-core-routers
  gather_facts: False
  connection: paramiko
  serial: 1
  tasks:
    - include: ../roles/common-mikrotik-routers/tasks/query-ros.yml
    - include: ../roles/mikrotik-cell-core-routers/tasks/main.yml
  vars:
    ignore_ip_address: yes
