---
- hosts: linux_fresh
  vars:
  tasks:
    - include: ../roles/common-linux/tasks/install_ntp.yml
    - include: ../roles/common-linux/tasks/install_postfix.yml
    - include: ../roles/common-linux/tasks/setup_dns.yml
  handlers:
  - include: ../roles/common-linux/handlers/handlers.yml
