---
- hosts: linux
  tasks:
  - include: ../roles/common-linux/tasks/add_users_groups.yml
  - include: ../roles/common-linux/tasks/restrict_ssh.yml
  handlers:
  - include: ../roles/common-linux/handlers/handlers.yml
