---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: test.missing.users
  - name: test.extra.users
  - name: test.group.change
provisioner:
  name: ansible
verifier:
  name: ansible
