---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: test.missing.users
  - name: test.extra.users
  - name: test.group.change
provisioner:
  name: ansible
  log: True
verifier:
  name: ansible
