---
- include: query-ros.yml

- name: Configure temp DNS servers before upgrade
  raw: /ip dns set servers=8.8.8.8,8.8.4.4

- include: upgrade-ros.yml

- name: Copy netadmin certificates to router
  raw: "/tool fetch url=\"{{ KEYS_URL }}{{ item }}.key\""
  with_items: NETOPS_USERS
  tags:
    - common
    - import

- name: Copy limted user certificates to router
  raw: "/tool fetch url=\"{{ KEYS_URL }}{{ item }}.key\""
  with_items: LIMITED_USERS
  tags: 
    - common
    - import

- name: Create template for common changes
  local_action: template src=common.j2 dest=roles/common-mikrotik-routers/generated-scripts/common.rsc backup=no
  tags:
    - generate
    - common

- name: Copy common changes script to router
  local_action: command scp -P {{ ansible_ssh_port }} roles/common-mikrotik-routers/generated-scripts/common.rsc {{ ansible_ssh_host |default(inventory_hostname) }}:/
  tags:
    - import
    - common

- name: "import script on device"
  raw: "/import verbose=yes common.rsc"
  tags: 
    - import
    - common
  register: import_result

- name: "import script on device failed"
  action: fail msg="importing script common.rsc on {{ inventory_hostname }} failed"
  tags: 
    - import
    - common
  when: "'failure:' in import_result.stdout"

- name: "remove script from device"
  raw: "/file remove common.rsc"
  tags: 
    - cleanup
    - common

- name: remove script from generated-scripts directory
  local_action: file path=./roles/common-mikrotik-routers/generated-scripts/common.rsc state=absent
  tags: 
    - cleanup
    - common
