---
- include: management-user-creation.yml
- include: upgrade-ros.yml

- name: "query device for hardware"
  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }} "/system routerboard print"
  tags: 
    - research
  register: routerboard_details

- name: Copy netadmin certificates to router
  action: command scp -P {{ ansible_ssh_port }} ./roles/common-mikrotik-routers/files/key-dsa-{{ item }}.txt {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/
  with_items: "{{ NETOPS_USERS }}"
  tags: 
    - common
    - import

- name: Create template for common changes
  template: src=common.j2 dest=./roles/common-mikrotik-routers/generated-scripts/common.rsc backup=no
  tags:
    - generate
    - common

- name: Copy common changes script to router
  action: command scp -P {{ ansible_ssh_port }} ./roles/common-mikrotik-routers/generated-scripts/common.rsc {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/
  tags:
    - import
    - common

- name: "import script on device"
  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }} "/import verbose=yes common.rsc"
  tags: 
    - import
    - common
  register: import_result

- name: "import script on device failed"
  action: fail msg="importing script common.rsc on {{ inventory_hostname }} failed"
  tags: 
    - import
    - common
  when: "'failure:' in import_result.stdout"

- name: "remove script from device"
  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }} "/file remove common.rsc"
  tags: 
    - cleanup
    - common

- name: remove script from generated-scripts directory
  action: file path=./roles/common-mikrotik-routers/generated-scripts/common.rsc state=absent
  tags: 
    - cleanup
    - common
