---
- name: Copy netadmin certificates to router
  action: command scp -P {{ ansible_ssh_port }} ./roles/common-mikrotik-routers/files/{{ item }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/
  with_items: "[advanced-tools-6.29.1-mipsbe.npk, calea-6.29.1-mipsbe.npk, dhcp-6.29.1-mipsbe.npk, gps-6.29.1-mipsbe.npk, hotspot-6.29.1-mipsbe.npk, ipv6-6.29.1-mipsbe.npk, lcd-6.29.1-mipsbe.npk, mpls-6.29.1-mipsbe.npk, multicast-6.29.1-mipsbe.npk, ntp-6.29.1-mipsbe.npk, openflow-6.29.1-mipsbe.npk, ppp-6.29.1-mipsbe.npk, routeros-mipsbe-6.29.1.npk, routing-6.29.1-mipsbe.npk, security-6.29.1-mipsbe.npk, system-6.29.1-mipsbe.npk, ups-6.29.1-mipsbe.npk, user-manager-6.29.1-mipsbe.npk, wireless-6.29.1-mipsbe.npk, wireless-fp-6.29.1-mipsbe.npk]"
  tags: import
# make the with_items list using "ls -m *.npk"
#- name: Create template for common changes
#  template: src=common.j2 dest=./roles/common-mikrotik-routers/generated-scripts/common.rsc backup=no
#  tags: generate

#- name: Copy common changes script to router
#  action: command scp -P {{ ansible_ssh_port }} ./roles/common-mikrotik-routers/generated-scripts/common.rsc {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/
#  tags: import

#- name: "import script on device"
#  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }} "/import verbose=yes common.rsc"
#  tags: import
#  register: import_result

#- name: "import script on device failed"
#  action: fail msg="importing script common.rsc on {{ inventory_hostname }} failed"
#  tags: import
#  when: "'failure:' in import_result.stdout"

#- name: "remove script from device"
#  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }} "/file remove common.rsc"
#  tags: cleanup

#- name: remove script from generated-scripts directory
#  action: file path=./roles/common-mikrotik-routers/generated-scripts/common.rsc state=absent
#  tags: cleanup
