---
# Tell the mikrotik router to download software updates and reboot.
- name: Get current ROS version
  local_action: uri url=http://download2.mikrotik.com/routeros/LATEST.6 return_content=yes
  register: latest_routeros_version

- debug: msg="Latest ROS version is {{ latest_routeros_version.content }}"

- name: Download latest routeros
  raw: "/tool fetch url=http://download2.mikrotik.com/routeros/{{ latest_routeros_version.content.split(' ')[0] | trim }}/routeros-mipsbe-{{ latest_routeros_version.content.split(' ')[0] | trim }}.npk"
  tags: 
    - upgrade-ros

- name: Restarting router
  raw: "/system reboot"
  tags:
    - upgrade-ros

- name: Wait for server to restart
  local_action: wait_for host={{ ansible_ssh_host |default(inventory_hostname) }} port=22 delay=30
  tags:
    - upgrade-ros
- name: pause 15 seconds for things to settle down
  local_action: pause seconds=15
