---
# Tell the mikrotik router to download software updates and reboot.

- name: Upgrade routeros
  raw: "/system package update upgrade"
  tags: 
    - upgrade-ros

#- name: Check Upgrade status
#  raw: "/system package update print"
#  tags:
#    - upgrade-ros
#  register: ros-upgrade-status
#
#- debug: msg="{{ ros-upgrade-status }}"

- pause: seconds=30
  tags:
    - upgrade-ros

- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      delay=1
      timeout=300
  tags:
    - upgrade-ros
 
