---
  - get_url: url="http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb" dest=/tmp/erlang-solutions_1.0_all.deb
  - apt: deb=/tmp/erlang-solutions_1.0_all.deb
  - apt: name=erlang-nox=1:18.2 state=present update_cache=yes
  - get_url: url="http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server_3.6.0-1_all.deb" dest=/tmp/rabbitmq-server_3.6.0-1_all.deb
  - apt: deb=/tmp/rabbitmq-server_3.6.0-1_all.deb
  - name: Set rabbitmq-server to run on boot
    shell: update-rc.d rabbitmq-server defaults
