---
- name: query device for hardware
  raw: "/system routerboard print"
  tags:
    - research
  register: routerboard_details
- debug: msg=routerboard_details.stdout

- name: query device for health and version
  raw: "/system resource print"
  tags:
    - research
  register: routeros_details
- debug: msg=routeros_details.stdout

- name: Create template for common changes
  local_action: template src=ptp.j2 dest=/tmp/ptp.rsc backup=no
  tags: 
    - generate
    - ptp

- name: Copy common changes script to router
  local_action: command scp -P {{ ansible_ssh_port }} /tmp/ptp.rsc {{ scp_user }}@{{ ansible_ssh_host }}:/
  tags: 
    - import
    - ptp

- name: "import script on device"
  raw: "/import verbose=yes ptp.rsc"
  tags:
    - import
    - ptp 
  register: import_result

- name: "import script on device failed"
  action: fail msg="importing script ptp.rsc on {{ inventory_hostname }} failed"
  tags:
    - import
    - ptp
  when: "'failure:' in import_result.stdout"

- name: "remove script from device"
  raw: "/file remove ptp.rsc"
  tags:
    - cleanup
    - ptp

- name: remove script from generated-scripts directory
  local_action: file path=/tmp/ptp.rsc state=absent
  tags:
    - cleanup
    - ptp
