- name: Add gqrx ppa
  apt_repository: repo={{item}} state=present
  with_items:
    - 'ppa:bladerf/bladerf'
    - 'ppa:ettusresearch/uhd'
    - 'ppa:myriadrf/drivers'
    - 'ppa:myriadrf/gnuradio'
    - 'ppa:gqrx/gqrx-sdr'

- name: Update and upgrade
  apt: upgrade=dist update_cache=yes

- name: Install prerequesites
  apt: pkg={{item}} state=installed
  with_items:
    - python2.7-dev 
    - python-pip
    - gnuradio 
    - gr-osmosdr 
    - rtl-sdr 
    - gr-air-modes 
    - multimon 
    - build-essential 
    - python-twisted 
    - python-txws 
    - git

- name: Install optional prereqs
  apt: pkg={{item}} state=installed
  with_items:
    - apache2
  tags: redirect

- name: Install shinysdr redirect
  template: src=apache_redirect.j2 dest=/etc/apache2/sites-enabled/000-default.conf mode=0777 owner=root group=root
  notify: Restart apache2
  tags: redirect

- name: Install prerequesites
  pip: name=ephem

- name: Install optional prereqs
  apt: pkg={{item}} state=installed
  with_items:
    - cmake
    - libboost-all-dev
    - libcppunit-dev
    - liblog4cpp5-dev
    - swig
    - pkg-config
    - gnuradio-dev
    - doxygen
    - libsndfile1-dev
  tags: gr-dsd

- name: Install optional prereqs
  apt: pkg={{item}} state=installed
  with_items:
    - libpulse-dev
  tags: multimon-ng

# build gr-dsd

- name: Clone gr-dsd
  git: repo=https://github.com/argilo/gr-dsd.git
       dest=/tmp/gr-dsd/
       accept_hostkey=yes
       force=yes
  tags: gr-dsd

- name: Build gr-dsd
  command: "{{ item }} chdir=/tmp/gr-dsd/"
  with_items:
    - "cmake ."
    - make
    - "make install"
    - ldconfig
  tags: gr-dsd

# build multimon-ng

- name: Clone multimon-ng
  git: repo=https://github.com/EliasOenal/multimon-ng.git
       dest=/tmp/multimon-ng/
       accept_hostkey=yes
       force=yes
  tags: multimon-ng

- name: Create build directory for multimon-ng
  file: path=/tmp/multimon-ng/build state=directory

- name: Build multimon-ng
  command: "{{ item }} chdir=/tmp/multimon-ng/build/"
  with_items:
    - qmake ../multimon-ng.pro
    - make
    - sudo make install
  tags: multimon-ng

# build shinysdr

- name: Clone shinysdr
  git: repo=https://github.com/kpreid/shinysdr.git 
       dest=/usr/local/src/shinysdr/
       accept_hostkey=yes
       force=yes

- name: Build shinysdr
  command: "{{ item }} chdir=/usr/local/src/shinysdr/"
  with_items:
    - sh fetch-js-deps.sh

# ShinySDR references the jasmine repo @ fd914337925a1e2729e2583a1023b2293d54ca55 which contains a recursive link. This is a workaround.
- name: Fix issue with infinite link
  file: path=/usr/local/src/shinysdr/shinysdr/deps/jasmine/pages state=absent

- name: Change owner of shinysdr
  file: path=/usr/local/src/shinysdr/ owner=root group=root mode=0755 recurse=yes

- name: Install shinysdr config
  template: src=roles/shinysdr/templates/shinysdr.j2 dest=/usr/local/src/shinysdr/config mode=0755 owner=root group=root

- name: Install shinysdr restart script
  template: src=roles/shinysdr/templates/shinysdr-restart.j2 dest=/usr/local/src/shinysdr/shinysdr-restart.sh mode=0755 owner=root group=root

- name: Add cron job to start
  cron: name="Restart shinysdr every 5 mins" minute="*/5" job="/usr/local/src/shinysdr/shinysdr-restart.sh"

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes
 
- name: Add apache iptable rule
  lineinfile: 
    dest=/etc/rc.local 
    line="iptables -A INPUT -p tcp --dport http -j ACCEPT"
    insertbefore="-----ROLE RULES END-----"
    state="present"         
  when: iptablesrules.stdout.find("http") == -1
  tags: redirect

- name: Add apache iptable rule
  lineinfile: 
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 8100 -j ACCEPT"
    insertbefore="-----ROLE RULES END-----"
    state="present"
  when: iptablesrules.stdout.find("8100") == -1

- name: Add apache iptable rule
  lineinfile: 
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 8101 -j ACCEPT"
    insertbefore="-----ROLE RULES END-----"
    state="present"
  when: iptablesrules.stdout.find("8101") == -1

- name: Execute /etc/rc.local to place iptables rules
  command: /etc/rc.local

