---
# vars file for users
users_admin:
  - eo
  - nigel
  - tom
users_user:
  - monitoring
group_admin: hamadmin
group_user: ham
authorized_key_scheme: https
authorized_key_location: monitoring.hamwan.net/keys/
