---
- set_fact:
    ether1_ip:  "{{ lookup('dig', 'ether1.' + inventory_hostname + './A', wantlist=True)[0] }}"

- name: Create template for common changes
  local_action: template src=cell-core-router.j2 dest=./roles/mikrotik-cell-core-routers/generated-scripts/cell-core-router.rsc backup=no
  tags: 
    - generate
    - cell-core-router

- name: Copy common changes script to router
  local_action: command scp -P {{ ansible_ssh_port|default('22') }} ./roles/mikrotik-cell-core-routers/generated-scripts/cell-core-router.rsc {{ ansible_ssh_host|default(inventory_hostname) }}:/
  tags: 
    - import
    - cell-core-router

- name: "import script on device"
  raw: "/import verbose=yes cell-core-router.rsc"
  tags: 
    - import
    - cell-core-router
  register: import_result

- name: "import script on device failed"
  action: fail msg="importing script cell-core-router.rsc on {{ inventory_hostname }} failed"
  tags: 
    - cell-core-router
    - import
  when: "'failure:' in import_result.stdout"

- name: "remove script from device"
  raw: "/file remove cell-core-router.rsc"
  tags: 
    - cell-core-router
    - cleanup

- name: remove script from generated-scripts directory
  local_action: file path=./roles/mikrotik-sector-routers/generated-scripts/cell-core-rotuer.rsc state=absent
  tags: 
    - cleanup
    - cell-core-router
