---
- name: Create template for common changes
  template: src=cell-core-router.j2 dest=./roles/mikrotik-cell-core-routers/generated-scripts/cell-core-router.rsc backup=no
  tags: 
    - generate
    - cell-core-router

- name: Copy common changes script to router
  action: command scp -P {{ ansible_ssh_port }} ./roles/mikrotik-cell-core-routers/generated-scripts/cell-core-router.rsc {{ ansible_ssh_host }}:/
  tags: 
    - import
    - cell-core-router

- name: "import script on device"
  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_host }} "/import verbose=yes cell-core-router.rsc"
  tags: 
    - import
    - cell-core-router
  register: import_result

- name: "import script on device failed"
  action: fail msg="importing script cell-core-router.rsc on {{ inventory_hostname }} failed"
  tags: 
    - cell-core-router
    - import
  when: "'failure:' in import_result.stdout"

- name: "remove script from device"
  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_host }} "/file remove cell-core-router.rsc"
  tags: 
    - cell-core-router
    - cleanup

- name: remove script from generated-scripts directory
  action: file path=./roles/mikrotik-sector-routers/generated-scripts/cell-core-rotuer.rsc state=absent
  tags: 
    - cleanup
    - cell-core-router
