---
# Install deb for unifi-video

- name: Add apt-key
  apt_key: url=http://www.ubnt.com/downloads/unifi-video/apt/unifi-video.gpg.key state=present

- name: Generate deb source file
  template:
    backup=no
    dest=/etc/apt/sources.list.d/unifi-video.list
    src=unifi-video.j2
    mode="u=rw,g=r,o=r"

- name: Ensure unifi-video is installed
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - unifi-video
  tags: unifi-video

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes

- name: Add iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 7080 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("7080") == -1

- name: Add iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 7443 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("7443") == -1

- name: Add iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 7445 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("7445") == -1

- name: Add iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 7446 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("7460") == -1

- name: Add iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 7447 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("7447") == -1

- name: Execute /etc/rc.local to place iptables rules
  command: /etc/rc.local
  notify: Restart unifi-video
