---
# tasks for common settings

- name: call common task template
  block:
    - name: collect facts
      ansible.builtin.include_tasks:
        file: get_facts.yml
      loop: "{{ routeros_facts }}"

    - name: common settings
      ansible.builtin.include_tasks:
        file: check_and_set_value.yml
      loop: "{{ settings.simple_settings }}"

    - name: v6 common settings
      ansible.builtin.include_tasks:
        file: check_and_set_value.yml
      loop: "{{ settings.v6_simple_settings }}"
      when: routeros_version is match("^6.")

    - name: v7 common settings
      ansible.builtin.include_tasks:
        file: check_and_set_value.yml
      loop: "{{ settings.v7_simple_settings }}"
      when: routeros_version is match("^7.")
