---
- apt_repository: repo='ppa:libreoffice/libreoffice-4-4'
- apt_repository: repo='ppa:mc3man/trusty-media'

- apt_key: url=http://ubuntu.bigbluebutton.org/bigbluebutton.asc state=present
- apt_repository: repo='deb http://ubuntu.bigbluebutton.org/trusty-1-0/ bigbluebutton-trusty main' state=present

- name: Ensure prereqs are installed
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - software-properties-common
    - build-essential
    - git-core
    - checkinstall
    - yasm
    - texi2html
    - libvorbis-dev
    - libx11-dev
    - libvpx-dev
    - libxfixes-dev
    - zlib1g-dev
    - pkg-config
    - netcat
    - libncurses5-dev
    - ffmpeg
    - bigbluebutton
    - bbb-check
    - bbb-demo

- name: Enable webrtc
  shell: bbb-conf --enablewebrtc

- name: Define server name
  shell: bbb-conf --setip {{ inventory_hostname }}

- name: Update nginx site config to use the proper url
  lineinfile: dest=/etc/nginx/sites-enabled/bigbluebutton regexp=server_name line="server_name videoconf.{{ LOCALE_DOMAIN }} {{ inventory_hostname }} {{ lookup('dig', inventory_hostname) }} {{ lookup('dig', 'videoconferencing.' + LOCALE_DOMAIN) }};"

- name: restart
  shell: bbb-conf --clean
