---
- name: List iptables rules being added
  debug: var=iptables_input_accept_rules

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes

- name: Add iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p {{ item.protocol }} {% if item.port is defined %}--dport {{ item.port }}{% endif %} -j ACCEPT {{ '#' }}{{ item.name }}"
    insertbefore="-----ROLE RULES END-----"
    state="present"
  when: "iptablesrules.stdout.find(item.name) == -1"
  with_items: "{{ iptables_input_accept_rules }}"

- name: Execute /etc/rc.local to place iptables rules
  command: /etc/rc.local
