- name: Install alertmanager
  docker:
    name: alertmanager
    image: prom/alertmanager:dev
    state: reloaded
    pull: always
    ports:
    - "9093:9093"
    volumes:
    - /srv/alertmanager:/etc/alertmanager

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes

- name: Add grafana iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 9093 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("9093") == -1  
