- name: Ensure blackbox_exporter path exists
  file: path=/srv/blackbox_exporter state=directory

- name: Generate default script
  template:
    backup=no
    dest=/srv/blackbox_exporter/blackbox.yml
    src=blackbox_exporter_config.j2
    mode="u=rw,g=r,o=r"

- name: Install blackbox exporter
  docker:
    name: blackbox_exporter
    image: prom/blackbox-exporter
    state: reloaded
    pull: always
    command: -config.file=/config/blackbox.yml
    ports:
    - "9115:9115"
    volumes:
    - /srv/blackbox_exporter:/config

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes

- name: Add blackbox iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 9115 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("9115") == -1  
