- name: Ensure prepreqs are installed
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - nginx

- name: Deactivate the default nginx site
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Generate site file
  template:
    backup=no
    dest=/etc/nginx/sites-available/prometheus
    src=nginx_site.j2
    force=yes

- name: Activate the site file
  file:
    src=/etc/nginx/sites-available/prometheus
    dest=/etc/nginx/sites-enabled/prometheus
    state=link
  notify: Restart nginx

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes

- name: Add prometheus-console iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 80 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("80") == -1

- name: Execute /etc/rc.local to place iptables rules
  command: /etc/rc.local

