- name: clone the repo
  git: repo=https://github.com/prometheus/snmp_exporter.git
       dest=/opt/prometheus/snmp_exporter
       force=yes

- name: remove previous if exists
  pip: 
    name=snmp_exporter
    state=absent

- name: build
  command: python setup.py install
  args:
    chdir: /opt/prometheus/snmp_exporter

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes

- name: Add prometheus-console iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 9116 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("9116") == -1

- name: Execute /etc/rc.local to place iptables rules
  command: /etc/rc.local

- name: Generate snmp_exporter config
  template:
    backup=no
    dest=/etc/prometheus/snmp_exporter.yml
    src=snmp_exporter_mikrotik.j2
    force=yes

- name: Generate default script
  template:
    backup=no
    dest=/etc/default/snmp_exporter
    src=generic_default.j2
    mode="u=rw,g=r,o=r"
    
- name: Generate init.d script
  template:
    backup=no
    dest=/etc/init.d/snmp_exporter
    src=snmp_exporter_initscript.j2
    force=yes
    mode="u=rwx,g=rx,o=rw"
  notify: Restart snmp_exporter 

- name: Setup blackbox_exporter to start on boot
  command: update-rc.d blackbox_exporter defaults
