- name: install prereqs
  apt: name=python-netsnmp state=present

- name: install snmp_exporter
  pip: name=snmp_exporter

- name: Get iptables rules
  command: /bin/cat /etc/rc.local
  register: iptablesrules
  always_run: yes

- name: Add prometheus-console iptable rule
  lineinfile:
    dest=/etc/rc.local
    line="iptables -A INPUT -p tcp --dport 9116 -j ACCEPT"
    insertbefore="iptables -P INPUT DROP"
    state="present"
  when: iptablesrules.stdout.find("9116") == -1

- name: Execute /etc/rc.local to place iptables rules
  command: /etc/rc.local

- name: Generate snmp_exporter config
  template:
    backup=no
    dest=/srv/mikrotik_snmp_exporter.yml
    src=snmp_exporter_mikrotik.j2
    force=yes
