---
# default values
ether_netmask: /28
ansible_ssh_host: "{{ lookup('dig', 'ether1.' + inventory_hostname + './A', wantlist=True)[0] }}"
routeros_setup_base_config: true
routeros_setup_users: true
field_day_core: false
client_node: false
field_day_ap: false
mikrotik_connect_flags: ""
upgrade_ros: true
