---
- name: Copy netadmin certificates to router
  local_action: command ssh -p {{ ansible_ssh_port }} {{ default_user|default(ansible_ssh_user) }}@{{ ansible_ssh_host|default(inventory_hostname) }} "/tool fetch url=\"{{ KEYS_URL }}{{ item }}.key\""
  with_items: NETOPS_USERS
  tags:
    - common
    - import

- name: Copy limted user certificates to router
  local_action: command ssh -p {{ ansible_ssh_port }} {{ default_user|default(ansible_ssh_user) }}@{{ ansible_ssh_host|default(inventory_hostname) }} "/tool fetch url=\"{{ KEYS_URL }}{{ item }}.key\""
  with_items: LIMITED_USERS
  tags:
    - common
    - import

- name: Create temp directory
  local_action: shell mktemp
  register: mktemp

- name: Create template for common changes
  local_action: template src=common.j2 dest={{ mktemp.stdout }} backup=no
  tags:
    - generate
    - common

- name: Copy common changes script to router
  local_action: command scp -P {{ ansible_ssh_port }}  {{ mktemp.stdout }} {{ default_user|default(ansible_ssh_user) }}@{{ ansible_ssh_host|default(inventory_hostname) }}:/common.rsc
  tags:
    - import
    - common

- name: "import script on device"
  local_action: command ssh -p {{ ansible_ssh_port }} {{ default_user|default(ansible_ssh_user) }}@{{ ansible_ssh_host|default(inventory_hostname) }} "/import verbose=yes common.rsc"
  tags:
    - import
    - common
  register: import_result

- name: "import script on device failed"
  action: fail msg="importing script common.rsc on {{ inventory_hostname }} failed"
  tags:
    - import
    - common
  when: "'failure:' in import_result.stdout"

- name: remove script from generated-scripts directory
  local_action: file path={{ mktemp.stdout }} state=absent
  tags:
    - cleanup
    - common
