---
- name: Create temp file
  local_action: shell mktemp
  register: mktemp
  
- name: Create template for common changes
  local_action: template src=field_day_core.j2 dest={{ mktemp.stdout }}  backup=no
  tags:
    - generate

- name: Copy field_day_core changes script to router
  local_action: command scp -P {{ mikrotik_port }} {{ mktemp.stdout }} {{ mikrotik_user }}@{{ mikrotik_host }}:/field_day_core.rsc
  tags:
    - import

- name: Import field_day_core changes script on device
  local_action: command ssh -p {{ mikrotik_port }} {{ mikrotik_user }}@{{ mikrotik_host }} "/import verbose=yes field_day_core.rsc"
  tags:
    - import
  register: import_result

- name: Importing field_day_core changes failed!
  action: fail msg="importing script field_day_core.rsc on {{ inventory_hostname }} failed"
  tags:
    - import
  when: "'failure:' in import_result.stdout"

- name: Remove field_day_core changes script from device
  local_action: command ssh -p {{ mikrotik_port }} {{ mikrotik_user }}@{{ mikrotik_host }} "/file remove field_day_core.rsc"
  tags:
    - cleanup

- name: Remove field_day_core changes script from local tmp dir
  local_action: file path={{ mktemp.stdout }} state=absent
  tags:
    - cleanup
