---
- include: query.yml
  tags: [query]

- include: upgrade_ros.yml
  tags: [upgrade_ros]

- include: basic_config.yml
  tags: [basic_config]
  when: routeros_setup_base_config == true

- include: field_day_core.yml
  tags: [field_day_core]
  when: field_day_core == true

- include: client_node.yml
  tags: [client_node]
  when: client_node == true

- include: cap.yml
  tags: [cap]
  when: field_day_ap == true
