---
- name: query device for hardware
  local_action: command ssh -p {{ ansible_ssh_port }} {{ default_user|default(ansible_ssh_user) }}@{{ ansible_ssh_host|default(inventory_hostname) }} "/system routerboard print"
  tags:
    - research
  register: routerboard_details
- debug: msg=routerboard_details.stdout

- name: query device for health and version
  local_action: command ssh -p {{ ansible_ssh_port }} {{ default_user|default(ansible_ssh_user) }}@{{ ansible_ssh_host|default(inventory_hostname) }} "/system resource print"
  tags:
    - research
  register: routeros_details
- debug: msg=routeros_details.stdout
