---
  - rabbitmq_vhost: name=/sensu state=present
  - rabbitmq_user: user=sensu
                 password={{ monitor_rabbitmq_secret }}
                 vhost=/sensu
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

  - lineinfile: dest=/etc/default/rabbitmq-server line="ulimit -n 65536"
    notify: restart rabbitmq
