---
- hosts: prometheus-server
#  vars: 
#    prometheus_components: ["node_exporter", "prometheus", "alertmanager"]
#    prometheus_alertmanager_url: "http://localhost:9093/"
#    prometheus_alertmanager_conf: ../roles/prometheus/templates/alertmanager.conf.j2
#    prometheus_conf_main: ../roles/prometheus/templates/prometheus.yml.j2
#  roles:
#   - williamyeh.prometheus
  sudo: yes
  tasks:
#   - include: ../roles/prometheus/tasks/install_prometheus.yml
#   - include: ../roles/prometheus/tasks/install_grafana.yml
#   - include: ../roles/prometheus/tasks/install_alertmanager.yml
#   - include: ../roles/prometheus/tasks/install_blackbox_exporter.yml
   - include: ../roles/prometheus/tasks/install_snmp_exporter.yml
#  handlers:
#   - include: ../roles/prometheus/handlers/handlers.yml
