---
- hosts: mikrotik-sector-routers
  gather_facts: False
  connection: paramiko
  tasks:
    - include: ../roles/common-mikrotik-routers/tasks/main.yml
    - include: ../roles/mikrotik-sector-routers/tasks/main.yml
  vars:
    ignore_ospf_and_ip_address: yes
  vars_files:
    group_vars/
