---
- hosts: quagga
  vars:
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: ../roles/quagga-anycast/tasks/setup.yml
    - include: ../roles/unbound/tasks/setup.yml
  vars_prompt:
    host_cidr: "CIDR (numbers only)"
    ospf_password: "OSPF Password"
