---
- name: Create template for common changes
  template: src=sector.j2 dest=./roles/mikrotik-sector-routers/generated-scripts/sector.rsc backup=no
  tags: generate

- name: Copy common changes script to router
  action: command scp -P {{ ansible_ssh_port }} ./roles/mikrotik-sector-routers/generated-scripts/sector.rsc {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/
  tags: import

- name: "import script on device"
  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }} "/import verbose=yes sector.rsc"
  tags: import
  register: import_result

- name: "import script on device failed"
  action: fail msg="importing script sector.rsc on {{ inventory_hostname }} failed"
  tags: import
  when: "'failure:' in import_result.stdout"

- name: "remove script from device"
  action: command ssh -p {{ ansible_ssh_port }} {{ ansible_ssh_user }}@{{ ansible_ssh_host }} "/file remove sector.rsc"
  tags: cleanup

#- name: remove script from generated-scripts directory
#  action: file path=./roles/mikrotik-sector-routers/generated-scripts/sector.rsc state=absent
#  tags: cleanup
